---
# tasks file for gangtise
- name: 在 node 节点创建相关目录
  file: path={{ item }} state=directory
  with_items:
  - /opt/gangtise/

# DNS文件中部分参数根据hosts文件设置而定，因此需要用template模块替换参数
- name: 准备 gangtise 的部署文件
  template: src={{ item }}.yaml.j2 dest=/opt/gangtise/{{ item }}.yaml
  with_items:
  - eureka
  - gangtise-auth-service
  - gangtise-gateway-service
  - gangtise-userinfo-service
  - gts-keyboard-yhty
  - ignite
  - quark-control-server
  - quark-maxwell
  - quark-response-client
  - spring-app-namespace
  - spring-config

- name: 获取所有已经创建的POD信息
  command: "{{ bin_dir }}/kubectl get pod --all-namespaces"
  register: pod_info
  run_once: true

- name: 创建配置信息部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/{{ item }}.yaml"
  with_items:
  - spring-app-namespace
  - spring-config
  run_once: true

- name: 创建注册中心部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/eureka.yaml"
  run_once: true

- name: 创建网关部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/gangtise-gateway-service.yaml"
  run_once: true

- name: 创建OAuth部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/gangtise-auth-service.yaml"
  run_once: true

- name: 创建用户信息部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/gangtise-userinfo-service.yaml"
  run_once: true

- name: 创建按键精灵部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/gts-keyboard-yhty.yaml"
  run_once: true

- name: 创建ignite部署
  shell: |
    "{{ bin_dir }}/kubectl apply -f /opt/gangtise/ignite.yaml"
    "{{ bin_dir }}/kubectl exec -it ignite-0 -n ignite -- ./apache-ignite/bin/control.sh --activate --yes"
  run_once: true

- name: 创建ignite控制台部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/quark-control-server.yaml"
  run_once: true

- name: 创建ignite客户端服务部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/quark-response-client.yaml"
  run_once: true

- name: 创建maxwell部署
  shell: "{{ bin_dir }}/kubectl apply -f /opt/gangtise/quark-maxwell.yaml"
  run_once: true

- name: 创建kafka部署
  shell: ""
  run_once: true

